## ADT Lab2
#### Shivali Mate
Link: https://colab.research.google.com/drive/1m_2mKmKDN-dMWQ_xai-Q5_xY7lqoObYE

In [ ]:
#importing required libraries
import sqlite3
import pandas as pd
from IPython.display import display

In [ ]:
# Create a connection to the SQLite database (1 points)
conn = sqlite3.connect('NetFlix.db')
c = conn.cursor()

In [ ]:
# Create a connection to the SQLite database (1 points)
conn2 = sqlite3.connect('spotify_top50_2021.db')
c = conn.cursor()

In [ ]:
# Load data from CSV files (1 points)
spotify_df = pd.read_csv("spotify_top50_2021.csv")
netflix_df = pd.read_csv('NetFlix.csv')

In [ ]:
# Create tables and insert data
spotify_df.to_sql('spotify_songs', conn, if_exists='replace', index=False)
netflix_df.to_sql('netflix_shows', conn, if_exists='replace', index=False)

7787


## Q1. Given a Spotify dataset containing various metrics for songs, retrieve the top 5 songs ranked by their popularity. (1 points)

In [ ]:
c.execute('''select track_name, artist_name, popularity
from spotify_songs
order by popularity desc
limit 5;

''')

df = pd.DataFrame(c.fetchall(), columns=['Track', 'Artist', 'Popularity'])
display(df)

        Track          Artist  Popularity
0    good 4 u  Olivia Rodrigo          95
1  Bad Habits      Ed Sheeran          95
2       Woman        Doja Cat          95
3  Heat Waves   Glass Animals          94
4    Yonaguni       Bad Bunny          94


##Q2. Identify and list all songs from the dataset that have a danceability score exceeding 0.7. Ensure that each song included meets this criterion based on its danceability rating. (1 points)

In [ ]:
c.execute('''select track_name, artist_name, danceability
from spotify_songs
where danceability > 0.7;

''')
df = pd.DataFrame(c.fetchall(), columns=['Track', 'Artist', 'Danceability'])
display(df)

,Track,Artist,Danceability
0,Levitating (feat. DaBaby),Dua Lipa,0.702
1,Kiss Me More (feat. SZA),Doja Cat,0.764
2,Heat Waves,Glass Animals,0.761
3,Beggin',Måneskin,0.714
4,Astronaut In The Ocean,Masked Wolf,0.778
5,DÁKITI,Bad Bunny,0.731
6,INDUSTRY BABY (feat. Jack Harlow),Lil Nas X,0.741
7,Bad Habits,Ed Sheeran,0.807
8,Butter,BTS,0.759
9,Todo De Ti,Rauw Alejandro,0.780
10,Mood (feat. iann dior),24kGoldn,0.701
11,The Business,Tiësto,0.798
12,Dynamite,BTS,0.746
13,Friday (feat. Mufasa & Hypeman) - Dopamine Re-...,Riton,0.824
14,Pepas,Farruko,0.762
15,positions,Ariana Grande,0.737
16,Bandido,Myke Towers,0.713
17,I WANNA BE YOUR SLAVE,Måneskin,0.750
18,RAPSTAR,Polo G,0.789
19,LA NOCHE DE ANOCHE,Bad Bunny,0.856
20,Streets,Doja Cat,0.749
21,Fiel,Los Legendarios,0.849
22,Don't Start Now,Dua Lipa,0.793
23,Lemonade (feat. Gunna Don Toliver & NAV),Internet Money,0.800
24,Woman,Doja Cat,0.824
25,Qué Más Pues?,J Balvin,0.903
26,Head & Heart (feat. MNEK),Joel Corry,0.734
27,34+35,Ariana Grande,0.830
28,Pareja Del Año,Sebastian Yatra,0.715

##Q3. Given a dataset from Spotify that includes various artists and their popularity scores, determine the average popularity score for each artist. This will help understand how popular each artist is on average across the dataset. (1 points)

In [ ]:
c.execute('''select artist_name, avg(popularity)
from spotify_songs
group by artist_name;

''')
df = pd.DataFrame(c.fetchall(), columns=['Artist', 'Avg Popularity'])
display(df)

               Artist  Avg Popularity
0            24kGoldn       89.000000
1       Ariana Grande       86.500000
2                 BTS       69.000000
3           Bad Bunny       89.333333
4          Bruno Mars       86.000000
5            Doja Cat       90.750000
6            Dua Lipa       86.500000
7     Duncan Laurence       78.000000
8          Ed Sheeran       95.000000
9             Farruko       86.000000
10             Giveon       86.000000
11      Glass Animals       94.000000
12       Harry Styles       90.000000
13     Internet Money       81.000000
14           J Balvin       79.000000
15         Joel Corry       86.000000
16      Justin Bieber       90.000000
17         Kali Uchis       87.000000
18      Lewis Capaldi       88.000000
19          Lil Nas X       90.000000
20    Los Legendarios       82.000000
21        Masked Wolf       77.000000
22        Myke Towers       82.000000
23           Måneskin       90.500000
24     Olivia Rodrigo       92.250000
25             Polo G       82.000000
26     Rauw Alejandro       69.000000
27              Riton       88.000000
28                SZA       86.000000
29    Sebastian Yatra       86.000000
30         Tate McRae       88.000000
31      The Kid LAROI       88.500000
32  The Neighbourhood       92.000000
33         The Weeknd       91.500000
34             Tiësto       88.000000

##Q4. Identify artists who have more than one song in the top 50 charts and count how many songs each of these artists have in the top 50. (2 points)

In [ ]:
c.execute('''select artist_name, count(*) as song_count
from spotify_songs
group by artist_name having song_count > 1
;

''')
df = pd.DataFrame(c.fetchall(), columns=['Artist', 'Song_Count'])
display(df)

           Artist  Song_Count
0   Ariana Grande           2
1             BTS           2
2       Bad Bunny           3
3        Doja Cat           4
4        Dua Lipa           2
5       Lil Nas X           2
6        Måneskin           2
7  Olivia Rodrigo           4
8   The Kid LAROI           2
9      The Weeknd           2

##Q5. Identify and list all the unique genres present in the Netflix dataset to understand the variety of content offered. (1 points)

In [ ]:
c.execute(''' select distinct genres
from netflix_shows

''')
df = pd.DataFrame(c.fetchall(), columns=['Genre'])
display(df)

                                                 Genre
0    International TV Shows, TV Dramas, TV Sci-Fi &...
1       Horror Movies, International Movies, Thrillers
2          Dramas, International Movies, Sports Movies
3                                             Comedies
4    British TV Shows, Docuseries, Science & Nature TV
..                                                 ...
487          Kids' TV, Reality TV, Science & Nature TV
488  International TV Shows, Spanish-Language TV Sh...
489                                   Sci-Fi & Fantasy
490  International TV Shows, TV Action & Adventure,...
491  Stand-Up Comedy & Talk Shows, TV Mysteries, TV...

[492 rows x 1 columns]

##Q6. Find all Netflix shows with "Blue" in the title. (1 points)

In [ ]:
c.execute(''' select title, genres
from netflix_shows
where title LIKE '%Blue%';

''')
df = pd.DataFrame(c.fetchall(), columns=['Title', 'Genre'])
display(df)

,Title,Genre
0,Blue Mountain State: The Rise of Thadland,Comedies
1,Blue Planet II,"British TV Shows, Docuseries, Science & Nature TV"
2,Blue Ruin,"Independent Movies, Thrillers"
3,Blue Streak,"Action & Adventure, Comedies"
4,Blue Valentine,"Dramas, Independent Movies, Romantic Movies"
5,Brave Blue World: Racing to Solve Our Water Cr...,"Documentaries, International Movies"
6,Colin Quinn: Red State Blue State,Stand-Up Comedy
7,GRANBLUE FANTASY the Animation,"Anime Series, International TV Shows"
8,Hunter in the Blue Side of Manchester,"Dramas, International Movies"
9,Mission Blue,Documentaries
10,Red vs. Blue,"TV Action & Adventure, TV Comedies, TV Sci-Fi ..."
11,The Blue Elephant 2,"Horror Movies, International Movies, Thrillers"
12,The Blue Planet: A Natural History of the Oceans,"British TV Shows, Docuseries, International TV..."
13,The Blue Umbrella,"Children & Family Movies, Dramas, Independent ..."
14,Auschwitz: Blueprints of Genocide,Documentaries
15,Blue Exorcist,"Anime Series, International TV Shows"
16,Blue Is the Warmest Color,"Dramas, Independent Movies, International Movies"
17,Blue Jasmine,"Comedies, Dramas, Independent Movies"
18,Blue Jay,"Dramas, Independent Movies, Romantic Movies"


##Q7. Find Spotify songs by Olivia Rodrigo or Dua Lipa. (2 points)

In [ ]:
c.execute('''select track_name, artist_name, popularity
from spotify_songs
where artist_name = 'Olivia Rodrigo' or artist_name = 'Dua Lipa';

''')
df = pd.DataFrame(c.fetchall(), columns=['Track', 'Artist', 'Popularity'])
display(df)

                       Track          Artist  Popularity
0            drivers license  Olivia Rodrigo          92
1                   good 4 u  Olivia Rodrigo          95
2  Levitating (feat. DaBaby)        Dua Lipa          89
3                    deja vu  Olivia Rodrigo          90
4                    traitor  Olivia Rodrigo          92
5            Don't Start Now        Dua Lipa          84

##Q8. Find songs on Spotify dataset that have a tempo between 100 and 120 beats per minute. (1 points)

In [ ]:
c.execute('''
select track_name, artist_name, tempo
from spotify_songs
where tempo > 100 AND tempo < 120;
''')
df = pd.DataFrame(c.fetchall(), columns=['Track', 'Artist', 'Tempo'])
display(df)

                        Track          Artist    Tempo
0   Levitating (feat. DaBaby)        Dua Lipa  102.977
1    Kiss Me More (feat. SZA)        Doja Cat  110.970
2                      DÁKITI       Bad Bunny  109.928
3             Save Your Tears      The Weeknd  118.051
4                      Butter             BTS  109.997
5                    Dynamite             BTS  114.044
6                     traitor  Olivia Rodrigo  100.607
7           Someone You Loved   Lewis Capaldi  109.891
8                       Woman        Doja Cat  107.998
9               Qué Más Pues?        J Balvin  102.014
10                      34+35   Ariana Grande  109.978

##Q9. Sort a list of Spotify songs first by their popularity in descending order, and then by their danceability in ascending order. (1 points)

In [ ]:
c.execute('''select track_name, artist_name, popularity, danceability
from spotify_songs
order by popularity desc, danceability asc;

''')
df = pd.DataFrame(c.fetchall(), columns=['Track', 'Artist', 'Popularity', 'Danceability'])
display(df)

,Track,Artist,Popularity,Danceability
0,good 4 u,Olivia Rodrigo,95,0.563
1,Bad Habits,Ed Sheeran,95,0.807
2,Woman,Doja Cat,95,0.824
3,Yonaguni,Bad Bunny,94,0.644
4,Heat Waves,Glass Animals,94,0.761
5,Blinding Lights,The Weeknd,93,0.514
6,Need to Know,Doja Cat,93,0.664
7,Beggin',Måneskin,93,0.714
8,traitor,Olivia Rodrigo,92,0.380
9,drivers license,Olivia Rodrigo,92,0.561
10,STAY (with Justin Bieber),The Kid LAROI,92,0.591
11,Sweater Weather,The Neighbourhood,92,0.612
12,deja vu,Olivia Rodrigo,90,0.442
13,Watermelon Sugar,Harry Styles,90,0.548
14,MONTERO (Call Me By Your Name),Lil Nas X,90,0.593
15,Peaches (feat. Daniel Caesar & Giveon),Justin Bieber,90,0.677
16,Save Your Tears,The Weeknd,90,0.680
17,INDUSTRY BABY (feat. Jack Harlow),Lil Nas X,90,0.741
18,Mood (feat. iann dior),24kGoldn,89,0.701
19,Levitating (feat. DaBaby),Dua Lipa,89,0.702
20,Someone You Loved,Lewis Capaldi,88,0.501
21,you broke me first,Tate McRae,88,0.667
22,positions,Ariana Grande,88,0.737
23,I WANNA BE YOUR SLAVE,Måneskin,88,0.750
24,Kiss Me More (feat. SZA),Doja Cat,88,0.764
25,The Business,Tiësto,88,0.798
26,Friday (feat. Mufasa & Hypeman) - Dopamine Re-...,Riton,88,0.824
27,telepatía,Kali Uchis,87,0.653
28,DÁKITI,Bad Bunny,87,0.731
29,Streets,Doja Cat,87,0.749
30,LA NOCHE DE ANOCHE,Bad Bunny,87,0.856
31,Good Days,SZA,86,0.436
32,Heartbreak Anniversary,Giveon,86,0.449
33,Leave The Door Open,Bruno Mars,86,0.586
34,Pareja Del Año,Sebastian Yatra,86,0.715
35,Head & Heart (feat. MNEK),Joel Corry,86,0.734
36,Pepas,Farruko,86,0.762
37,WITHOUT YOU,The Kid LAROI,85,0.662
38,34+35,Ariana Grande,85,0.830
39,Don't Start Now,Dua Lipa,84,0.793
40,Bandido,Myke Towers,82,0.713
41,RAPSTAR,Polo G,82,0.789
42,Fiel,Los Legendarios,82,0.849
43,Lemonade (feat. Gunna Don Toliver & NAV),Internet Money,81,0.800
44,Qué Más Pues?,J Balvin,79,0.903
45,Arcade,Duncan Laurence,78,0.453
46,Astronaut In The Ocean,Masked Wolf,77,0.778
47,Butter,BTS,71,0.759
48,Todo De Ti,Rauw Alejandro,69,0.780
49,Dynamite,BTS,67,0.746

## Q10. Identify Netflix shows that have a runtime longer than the average runtime of all shows on the platform. (2 points)

In [ ]:
c.execute(''' select title, duration
from netflix_shows
where duration > (select avg(duration)
from netflix_shows);

''')
df = pd.DataFrame(c.fetchall(), columns=['Title', 'Runtime'])
display(df)

                                          Title  Runtime
0                                          1920      143
1                                    3 Heroines      124
2     Blue Mountain State: The Rise of Thadland       90
3                                     Blue Ruin       90
4                                   Blue Streak       94
...                                         ...      ...
4713                            Blood Will Tell      113
4714                                       Blow      123
4715                  Blue Is the Warmest Color      180
4716                               Blue Jasmine       98
4717                                   Blue Jay       81

[4718 rows x 2 columns]

## Q11. Combine the titles of all Spotify songs and Netflix shows into a single list. Use the UNION operation to merge these two datasets, ensuring that each title appears only once in the final list. (2 points)

In [ ]:
c.execute(''' select title from netflix_shows
UNION ALL
select track_name from spotify_songs;

''')
df = pd.DataFrame(c.fetchall(), columns=['Title'])
display(df)

                                          Title
0                                            3%
1                                          1920
2                                    3 Heroines
3     Blue Mountain State: The Rise of Thadland
4                                Blue Planet II
...                                         ...
7832                              Qué Más Pues?
7833                  Head & Heart (feat. MNEK)
7834                                      34+35
7835                         you broke me first
7836                             Pareja Del Año

[7837 rows x 1 columns]

## Q12. Create a list where each Spotify song is paired with each Netflix show genre. The goal is to generate combinations of songs and genres to explore how different music might fit with various types of TV shows. (1 points)

In [ ]:
c.execute(''' select track_name, artist_name, genres
from spotify_songs, netflix_shows;

''')
df = pd.DataFrame(c.fetchall(), columns=['Track', 'Artist', 'Genre'])
display(df)

,Track,Artist,Genre
0,drivers license,Olivia Rodrigo,"International TV Shows, TV Dramas, TV Sci-Fi &..."
1,drivers license,Olivia Rodrigo,"Horror Movies, International Movies, Thrillers"
2,drivers license,Olivia Rodrigo,"Dramas, International Movies, Sports Movies"
3,drivers license,Olivia Rodrigo,Comedies
4,drivers license,Olivia Rodrigo,"British TV Shows, Docuseries, Science & Nature TV"
...,...,...,...
389345,Pareja Del Año,Sebastian Yatra,"International TV Shows, Reality TV"
389346,Pareja Del Año,Sebastian Yatra,"Anime Series, International TV Shows"
389347,Pareja Del Año,Sebastian Yatra,"Dramas, Independent Movies, International Movies"
389348,Pareja Del Año,Sebastian Yatra,"Comedies, Dramas, Independent Movies"
389349,Pareja Del Año,Sebastian Yatra,"Dramas, Independent Movies, Romantic Movies"

##Q13. Determine the average popularity of Spotify songs for each genre of Netflix shows by joining the Spotify songs and Netflix shows datasets. Use an INNER JOIN to match records where genres align. (2 points)

In [ ]:
c.execute('''select genres, avg(popularity)
from netflix_shows
INNER JOIN spotify_songs
on netflix_shows.title = spotify_songs.track_name
group by genres

''')
df = pd.DataFrame(c.fetchall(), columns=['Genre', 'Popularity'])
print(df)

Empty DataFrame
Columns: [Genre, Popularity]
Index: []